In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn import metrics
from os import listdir
from os.path import isfile, join
from sklearn.preprocessing import Normalizer
from sklearn.metrics import f1_score
import pickle

In [2]:
pathm="C:\\Users\\nilu1\\Desktop\\Code\\AndroidPattern\\Phone\\Using model\\"
pathmex = [f for f in listdir(pathm) if isfile(join(pathm, f))]
pathmex.sort()
# pathex=["Gyro_400_window_a29c08&66b325&b56522_1200.csv"]
# filem=pathmex[0]

In [3]:
path="C:\\Users\\nilu1\\Desktop\\Code\\AndroidPattern\\Phone\\Using\\"
pathex = [f for f in listdir(path) if isfile(join(path, f))]
pathex.sort()
# file=pathex[0]
for filem in pathmex:
    for file in pathex:
        ni=file.rfind("_")+1
        n=int(file[ni:].split(".")[0])
        nim=filem.rfind("_")+1
        nm=int(filem[nim:].split(".")[0])
        if(n!=nm):
            continue
        df=pd.read_csv(path+file)
        x_test = df.iloc[:, 0:n].values
        y_test = df.iloc[:, n].values
        logmodel=pickle.load(open(pathm+filem, 'rb'))
        y_pred = logmodel.predict(x_test)

        # print(y_pred,y)

        p = logmodel.predict_proba(x_test)
        nn = 3
        top_n = np.argsort(p)[:,:-nn-1:-1]
        print(filem)
        print(file)
        print(y_test)
        print(y_pred)
        print(top_n)
        print()
#         count=0
#         count12=0
#         for i in range(len(y_pred)):
#             if(y_test[i] in top_n[i]):
#                 count+=1
#             if(y_test[i] in top_n[i][:2]):
#                 count12+=1
#     #         print(y_test[i],top_n[i])
#         l=len(y_pred)
#         print(filem)
#         print(file)
#         print("f1score : ",f1_score(y_test, y_pred, average="micro"))
#         print("accuracy score : ", accuracy_score(y_test,y_pred))
#         print(count/l)
#         print("At position 1 or 2 : ",count12/l)
#         print(classification_report(y_test, y_pred))

mlp500_idenhide_Acc_woGyro_800_winuni_4b0c17&4b0c18_2400.sav
Acc_woGyro_800_winuni_4b0c23_02_19_21_PM_2400.csv
[0 1 2 3]
[7 5 7 5]
[[7 4 0]
 [5 3 7]
 [7 8 0]
 [5 8 4]]

mlp500_idenhide_Acc_woGyro_800_winuni_4b0c17&4b0c18_2400.sav
Acc_woGyro_800_winuni_4b0c23_02_20_11_PM_2400.csv
[0 1 2 3]
[7 7 7 8]
[[7 4 2]
 [7 4 0]
 [7 0 8]
 [8 0 5]]

mlp500_idenhide_Acc_woGyro_800_winuni_4b0c17&4b0c18_2400.sav
Acc_woGyro_800_winuni_4b0c23_02_21_26_PM_2400.csv
[0 1 2 3]
[7 0 4 7]
[[7 5 8]
 [0 7 8]
 [4 7 5]
 [7 4 2]]

mlp500_idenhide_Acc_woGyro_800_winuni_4b0c17&4b0c18_2400.sav
Acc_woGyro_800_winuni_4b0c23_02_22_33_PM_2400.csv
[0 1 2 3]
[4 7 7 7]
[[4 2 1]
 [7 1 4]
 [7 4 8]
 [7 0 6]]

mlp500_idenhide_Acc_woGyro_800_winuni_4b0c17&4b0c18_2400.sav
Acc_woGyro_800_winuni_4b0c23_02_23_10_PM_2400.csv
[0 1 2 3]
[7 4 7 7]
[[7 0 5]
 [4 7 1]
 [7 0 5]
 [7 5 2]]

mlp500_idenhide_Acc_woGyro_800_winuni_4b0c17&4b0c18_2400.sav
Acc_woGyro_800_winuni_4b0c23_02_24_54_PM_2400.csv
[0 1 2 3]
[4 7 7 7]
[[4 7 1]
 [7 4 0]
 [7 4 