In [1]:
import pandas as pd
import numpy as np
import os
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
# from sklearn.neighbors import NearestCentroid # 0.32
from sklearn.ensemble import RandomForestClassifier
from sklearn.multioutput import MultiOutputClassifier
from sklearn.utils import shuffle
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix,accuracy_score
from sklearn import metrics
from os import listdir
from os.path import isfile, join
from sklearn.preprocessing import Normalizer
from sklearn.metrics import f1_score

In [2]:
path="C:\\Users\\nilu1\\Desktop\\Code\\AndroidPattern\\Data\\Standardized\\"
pathex = [f for f in listdir(path) if isfile(join(path, f))]
score=[]

In [3]:
def setmultioutput(x):
    if(x==1):
        return [1,2,4]
    if(x==2):
        return [1,2,5]
    if(x==3):
        return [3,5,6]
    if(x==4):
        return [5,7,8]
    if(x==5):
        return [6,8,9]
    if(x==6):
        return [3,5,9]
    if(x==7):
        return [4,5,8]
    if(x==8):
        return [5,9,0]
    if(x==9):
        return [6,8,9]
    if(x==0):
        return [8,9,0]

In [4]:
for file in pathex:
    ni=file.rfind("_")+1
    n=int(file[ni:].split(".")[0])
    df=pd.read_csv(path+file)
    x = df.iloc[:, 0:n].values
    y = df.iloc[:, n].values
    X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.25, random_state=0)
    temp1=[]
    temp11=[]
    temp111=[]
    for i in range(len(y_train)):
        t=setmultioutput(y_train[i])
        temp1.append(t[0])
        temp11.append(t[1])
        temp111.append(t[2])
    temp2=[]
    temp22=[]
    temp222=[]
    for i in range(len(y_test)):
        t=setmultioutput(y_test[i])
        temp2.append(t[0])
        temp22.append(t[1])
        temp222.append(t[2])
    y_train=np.vstack((y_train, temp1, temp11,temp111)).T
    y_test=np.vstack((y_test, temp2, temp22,temp222)).T
    model = RandomForestClassifier(n_estimators=10, random_state=0, max_depth=10)
    logmodel = MultiOutputClassifier(model, n_jobs=-1)
    logmodel.fit(X_train, y_train)
    y_pred = logmodel.predict(X_train)
    print(file,end=" : ")
#     print(accuracy_score(y_train,y_pred))
    y_pred = logmodel.predict(X_test)
    for i in range(len(y_pred)):
        print(y_test[i],y_pred[i])
#     df = pd.DataFrame({'Actual': y_test, 'Predicted': y_pred})
#     score.append([f1_score(y_test, y_pred, average="micro"),file])
#     score.append([accuracy_score(y_test, y_pred),file])
#     print(df)
# score.sort(reverse=True)
# print("--------------------------Test : ----------------------------")
# for i in range(len(score)):
#     print(score[i][1]+" : "+str(score[i][0]))
# df

Acc_w_25_4vuni_66b325&b56522_9.csv : [9 6 8 9] [7 8 5 0]
[6 3 5 9] [7 4 5 8]
[6 3 5 9] [9 6 5 9]
[4 5 7 8] [4 4 7 8]
[4 5 7 8] [4 1 2 8]
[1 1 2 4] [1 1 2 4]
[3 3 5 6] [3 5 8 6]
[8 5 9 0] [6 1 5 6]
[1 1 2 4] [1 1 2 4]
[1 1 2 4] [1 1 2 4]
[9 6 8 9] [3 6 8 9]
[7 4 5 8] [0 4 5 8]
[4 5 7 8] [2 1 8 4]
[7 4 5 8] [2 1 2 8]
[0 8 9 0] [3 3 5 0]
[3 3 5 6] [8 5 9 6]
[6 3 5 9] [6 3 5 9]
[4 5 7 8] [2 3 7 8]
[6 3 5 9] [2 3 5 8]
[6 3 5 9] [7 5 5 8]
[8 5 9 0] [9 6 5 9]
[9 6 8 9] [3 3 5 9]
[6 3 5 9] [0 5 9 8]
[9 6 8 9] [6 6 8 9]
[5 6 8 9] [0 6 9 0]
[4 5 7 8] [8 5 7 8]
[6 3 5 9] [7 3 5 9]
[2 1 2 5] [0 6 9 0]
[5 6 8 9] [4 5 5 9]
[1 1 2 4] [1 1 2 4]
[8 5 9 0] [8 5 9 0]
[3 3 5 6] [3 3 5 9]
[5 6 8 9] [6 6 5 0]
[6 3 5 9] [8 3 5 9]
[5 6 8 9] [3 5 9 9]
[2 1 2 5] [2 1 2 5]
[7 4 5 8] [3 1 2 8]
[0 8 9 0] [8 3 9 0]
[5 6 8 9] [3 1 8 6]
[6 3 5 9] [6 3 5 9]
[1 1 2 4] [1 1 7 4]
[9 6 8 9] [5 6 8 9]
[4 5 7 8] [8 8 9 8]
[2 1 2 5] [4 5 7 8]
[7 4 5 8] [7 4 9 8]
[3 3 5 6] [6 3 5 9]
[9 6 8 9] [8 3 8 9]
[1 1 2 4] [1 1 2 4]
[9 

Acc_w_25_4v_66b325&b56522_9.csv : [9 6 8 9] [9 3 9 0]
[6 3 5 9] [7 4 5 8]
[6 3 5 9] [3 3 5 9]
[4 5 7 8] [2 1 2 8]
[4 5 7 8] [7 1 2 5]
[1 1 2 4] [1 1 2 4]
[3 3 5 6] [3 3 2 9]
[8 5 9 0] [6 8 5 9]
[1 1 2 4] [1 1 2 4]
[1 1 2 4] [1 1 2 4]
[9 6 8 9] [9 3 8 9]
[7 4 5 8] [7 4 5 8]
[4 5 7 8] [4 4 8 8]
[7 4 5 8] [4 5 7 5]
[0 8 9 0] [0 4 9 0]
[3 3 5 6] [3 3 5 0]
[6 3 5 9] [6 3 5 9]
[4 5 7 8] [4 5 5 8]
[6 3 5 9] [6 3 5 9]
[6 3 5 9] [4 5 5 8]
[8 5 9 0] [0 5 8 0]
[9 6 8 9] [5 3 5 9]
[6 3 5 9] [2 5 9 8]
[9 6 8 9] [5 6 5 9]
[5 6 8 9] [7 5 9 8]
[4 5 7 8] [4 5 5 8]
[6 3 5 9] [9 3 5 9]
[2 1 2 5] [9 6 8 9]
[5 6 8 9] [4 6 5 8]
[1 1 2 4] [1 1 2 4]
[8 5 9 0] [8 6 9 9]
[3 3 5 6] [6 3 5 9]
[5 6 8 9] [3 3 9 9]
[6 3 5 9] [5 3 5 9]
[5 6 8 9] [3 5 5 9]
[2 1 2 5] [2 1 2 5]
[7 4 5 8] [2 1 2 8]
[0 8 9 0] [8 5 5 0]
[5 6 8 9] [3 5 8 9]
[6 3 5 9] [3 3 5 6]
[1 1 2 4] [1 1 7 4]
[9 6 8 9] [6 6 8 9]
[4 5 7 8] [4 6 5 8]
[2 1 2 5] [4 5 5 8]
[7 4 5 8] [3 5 9 8]
[3 3 5 6] [2 3 5 9]
[9 6 8 9] [9 6 5 9]
[1 1 2 4] [1 1 2 4]
[9 6 8

Acc_w_25_window_66b325&b56522_75.csv : [9 6 8 9] [8 5 5 9]
[6 3 5 9] [0 8 5 0]
[6 3 5 9] [3 3 5 0]
[4 5 7 8] [4 5 2 8]
[4 5 7 8] [4 1 2 5]
[1 1 2 4] [1 1 2 4]
[3 3 5 6] [1 3 2 6]
[8 5 9 0] [0 4 9 0]
[1 1 2 4] [1 1 2 4]
[1 1 2 4] [1 5 2 8]
[9 6 8 9] [9 5 5 9]
[7 4 5 8] [4 1 9 8]
[4 5 7 8] [4 5 5 8]
[7 4 5 8] [2 5 7 8]
[0 8 9 0] [3 5 5 0]
[3 3 5 6] [8 3 5 6]
[6 3 5 9] [3 3 8 9]
[4 5 7 8] [4 5 7 8]
[6 3 5 9] [6 3 5 9]
[6 3 5 9] [2 6 7 8]
[8 5 9 0] [8 3 5 0]
[9 6 8 9] [6 3 8 0]
[6 3 5 9] [4 5 8 6]
[9 6 8 9] [5 5 5 0]
[5 6 8 9] [7 6 9 0]
[4 5 7 8] [7 5 5 8]
[6 3 5 9] [6 5 9 9]
[2 1 2 5] [7 6 9 9]
[5 6 8 9] [4 5 5 8]
[1 1 2 4] [1 1 2 4]
[8 5 9 0] [8 3 9 0]
[3 3 5 6] [6 3 5 6]
[5 6 8 9] [3 1 5 9]
[6 3 5 9] [5 3 5 9]
[5 6 8 9] [5 6 9 6]
[2 1 2 5] [2 1 2 5]
[7 4 5 8] [1 5 2 8]
[0 8 9 0] [3 5 9 0]
[5 6 8 9] [3 3 5 9]
[6 3 5 9] [6 3 5 9]
[1 1 2 4] [1 1 2 4]
[9 6 8 9] [6 6 8 9]
[4 5 7 8] [9 5 5 8]
[2 1 2 5] [7 8 5 9]
[7 4 5 8] [4 5 7 8]
[3 3 5 6] [6 1 2 9]
[9 6 8 9] [6 3 5 9]
[1 1 2 4] [1 1 2 4]
[

Acc_w_30_4vuni_66b325&b56522_9.csv : [9 6 8 9] [7 8 9 0]
[6 3 5 9] [6 3 5 9]
[6 3 5 9] [6 6 5 9]
[4 5 7 8] [4 5 7 8]
[4 5 7 8] [4 5 2 8]
[1 1 2 4] [1 1 2 4]
[3 3 5 6] [3 3 5 6]
[8 5 9 0] [9 6 8 8]
[1 1 2 4] [1 1 2 4]
[1 1 2 4] [2 1 2 4]
[9 6 8 9] [8 6 8 9]
[7 4 5 8] [6 4 7 8]
[4 5 7 8] [7 3 5 8]
[7 4 5 8] [2 5 7 8]
[0 8 9 0] [3 6 5 0]
[3 3 5 6] [3 3 5 6]
[6 3 5 9] [5 6 5 9]
[4 5 7 8] [7 1 2 8]
[6 3 5 9] [5 6 5 9]
[6 3 5 9] [5 3 8 0]
[8 5 9 0] [9 6 8 9]
[9 6 8 9] [9 6 8 9]
[6 3 5 9] [3 6 5 9]
[9 6 8 9] [9 6 5 9]
[5 6 8 9] [7 6 5 0]
[4 5 7 8] [4 5 2 8]
[6 3 5 9] [3 3 5 9]
[2 1 2 5] [6 3 9 9]
[5 6 8 9] [4 5 5 8]
[1 1 2 4] [1 1 2 4]
[8 5 9 0] [3 5 8 9]
[3 3 5 6] [3 3 5 9]
[5 6 8 9] [8 3 5 9]
[6 3 5 9] [3 3 5 9]
[5 6 8 9] [8 5 9 0]
[2 1 2 5] [2 1 2 5]
[7 4 5 8] [3 3 5 6]
[0 8 9 0] [0 5 8 8]
[5 6 8 9] [5 1 2 9]
[6 3 5 9] [9 6 8 9]
[1 1 2 4] [1 1 2 4]
[9 6 8 9] [6 3 5 9]
[4 5 7 8] [0 8 5 8]
[2 1 2 5] [8 5 9 9]
[7 4 5 8] [4 5 2 8]
[3 3 5 6] [6 3 5 0]
[9 6 8 9] [0 8 9 0]
[1 1 2 4] [1 1 2 4]
[9 

Acc_w_30_4v_66b325&b56522_9.csv : [9 6 8 9] [0 6 9 0]
[6 3 5 9] [6 3 5 9]
[6 3 5 9] [6 3 5 9]
[4 5 7 8] [4 1 7 8]
[4 5 7 8] [2 5 2 5]
[1 1 2 4] [1 1 2 4]
[3 3 5 6] [3 6 5 9]
[8 5 9 0] [0 8 9 9]
[1 1 2 4] [1 1 2 4]
[1 1 2 4] [1 1 2 4]
[9 6 8 9] [9 6 8 9]
[7 4 5 8] [7 4 5 8]
[4 5 7 8] [4 5 7 8]
[7 4 5 8] [7 4 7 8]
[0 8 9 0] [0 3 9 0]
[3 3 5 6] [3 3 5 6]
[6 3 5 9] [3 3 5 9]
[4 5 7 8] [4 1 5 8]
[6 3 5 9] [6 3 5 9]
[6 3 5 9] [4 5 5 8]
[8 5 9 0] [9 6 8 9]
[9 6 8 9] [5 6 5 9]
[6 3 5 9] [4 3 7 8]
[9 6 8 9] [5 3 5 9]
[5 6 8 9] [7 4 9 0]
[4 5 7 8] [7 5 5 8]
[6 3 5 9] [0 3 5 0]
[2 1 2 5] [6 6 5 0]
[5 6 8 9] [2 5 5 8]
[1 1 2 4] [1 1 2 4]
[8 5 9 0] [7 5 5 9]
[3 3 5 6] [6 3 5 9]
[5 6 8 9] [8 3 9 6]
[6 3 5 9] [5 3 8 9]
[5 6 8 9] [3 3 8 9]
[2 1 2 5] [2 1 2 5]
[7 4 5 8] [3 1 2 8]
[0 8 9 0] [9 6 8 0]
[5 6 8 9] [8 5 9 0]
[6 3 5 9] [6 3 5 9]
[1 1 2 4] [4 1 2 8]
[9 6 8 9] [5 3 5 9]
[4 5 7 8] [7 6 5 8]
[2 1 2 5] [8 5 8 8]
[7 4 5 8] [4 5 9 0]
[3 3 5 6] [6 3 5 9]
[9 6 8 9] [9 3 5 9]
[1 1 2 4] [1 1 2 4]
[9 6 8

Acc_w_30_window_66b325&b56522_90.csv : [9 6 8 9] [0 5 8 0]
[6 3 5 9] [6 4 5 0]
[6 3 5 9] [6 3 5 9]
[4 5 7 8] [2 1 7 5]
[4 5 7 8] [2 1 5 5]
[1 1 2 4] [1 1 2 4]
[3 3 5 6] [8 3 5 0]
[8 5 9 0] [0 5 5 0]
[1 1 2 4] [1 1 2 4]
[1 1 2 4] [1 1 2 4]
[9 6 8 9] [6 4 9 0]
[7 4 5 8] [1 5 5 0]
[4 5 7 8] [4 5 7 8]
[7 4 5 8] [4 4 5 8]
[0 8 9 0] [0 3 9 0]
[3 3 5 6] [3 3 5 6]
[6 3 5 9] [6 3 5 9]
[4 5 7 8] [7 5 5 8]
[6 3 5 9] [6 3 5 9]
[6 3 5 9] [4 3 5 8]
[8 5 9 0] [0 6 8 9]
[9 6 8 9] [5 6 5 9]
[6 3 5 9] [5 5 7 8]
[9 6 8 9] [5 6 9 9]
[5 6 8 9] [0 5 9 0]
[4 5 7 8] [7 5 5 8]
[6 3 5 9] [6 5 9 0]
[2 1 2 5] [7 6 5 0]
[5 6 8 9] [5 6 7 0]
[1 1 2 4] [1 1 2 4]
[8 5 9 0] [8 6 8 0]
[3 3 5 6] [6 3 5 9]
[5 6 8 9] [0 3 9 6]
[6 3 5 9] [5 3 8 9]
[5 6 8 9] [3 5 2 8]
[2 1 2 5] [2 1 2 5]
[7 4 5 8] [4 5 2 8]
[0 8 9 0] [8 3 9 0]
[5 6 8 9] [3 3 5 6]
[6 3 5 9] [9 6 5 9]
[1 1 2 4] [1 1 2 4]
[9 6 8 9] [5 6 5 9]
[4 5 7 8] [4 5 5 0]
[2 1 2 5] [4 5 5 8]
[7 4 5 8] [3 5 5 8]
[3 3 5 6] [2 8 8 9]
[9 6 8 9] [9 3 5 9]
[1 1 2 4] [1 1 2 4]
[

Gyro_25_4vuni_66b325&b56522_9.csv : [9 6 8 9] [3 6 8 9]
[6 3 5 9] [6 6 5 9]
[6 3 5 9] [2 6 5 9]
[4 5 7 8] [1 4 5 8]
[4 5 7 8] [4 5 7 8]
[1 1 2 4] [1 1 2 4]
[3 3 5 6] [3 3 9 0]
[8 5 9 0] [8 3 9 0]
[1 1 2 4] [2 5 2 8]
[1 1 2 4] [1 5 2 4]
[9 6 8 9] [9 6 8 0]
[7 4 5 8] [7 5 9 0]
[4 5 7 8] [2 1 2 8]
[7 4 5 8] [8 3 5 6]
[0 8 9 0] [0 8 9 0]
[3 3 5 6] [8 3 5 9]
[6 3 5 9] [6 6 5 9]
[4 5 7 8] [1 4 7 8]
[6 3 5 9] [5 3 8 9]
[6 3 5 9] [9 6 8 9]
[8 5 9 0] [6 3 5 9]
[9 6 8 9] [3 3 5 9]
[6 3 5 9] [3 3 8 9]
[9 6 8 9] [0 5 9 0]
[5 6 8 9] [6 6 5 9]
[4 5 7 8] [4 5 5 8]
[6 3 5 9] [0 8 9 0]
[2 1 2 5] [3 3 5 6]
[5 6 8 9] [2 5 2 8]
[1 1 2 4] [2 1 7 8]
[8 5 9 0] [8 5 5 0]
[3 3 5 6] [8 5 8 5]
[5 6 8 9] [8 5 9 0]
[6 3 5 9] [6 3 8 9]
[5 6 8 9] [6 6 9 9]
[2 1 2 5] [2 1 2 5]
[7 4 5 8] [4 5 7 8]
[0 8 9 0] [0 8 9 0]
[5 6 8 9] [8 5 5 0]
[6 3 5 9] [3 3 5 9]
[1 1 2 4] [1 5 2 4]
[9 6 8 9] [6 3 9 9]
[4 5 7 8] [4 5 7 8]
[2 1 2 5] [2 1 5 5]
[7 4 5 8] [7 4 5 9]
[3 3 5 6] [7 3 5 9]
[9 6 8 9] [5 5 9 9]
[1 1 2 4] [4 5 7 8]
[9 6

Gyro_25_4v_66b325&b56522_9.csv : [9 6 8 9] [2 3 5 6]
[6 3 5 9] [3 6 8 0]
[6 3 5 9] [3 3 5 9]
[4 5 7 8] [4 5 7 8]
[4 5 7 8] [1 1 7 8]
[1 1 2 4] [1 4 2 8]
[3 3 5 6] [3 3 5 6]
[8 5 9 0] [8 6 9 0]
[1 1 2 4] [7 4 7 8]
[1 1 2 4] [4 5 7 8]
[9 6 8 9] [9 3 8 9]
[7 4 5 8] [2 1 2 5]
[4 5 7 8] [1 5 2 8]
[7 4 5 8] [7 4 5 0]
[0 8 9 0] [0 8 9 0]
[3 3 5 6] [0 5 8 0]
[6 3 5 9] [6 3 8 9]
[4 5 7 8] [7 1 7 8]
[6 3 5 9] [9 6 5 9]
[6 3 5 9] [6 3 5 9]
[8 5 9 0] [8 6 9 9]
[9 6 8 9] [3 3 5 9]
[6 3 5 9] [6 6 5 9]
[9 6 8 9] [9 5 9 9]
[5 6 8 9] [5 6 8 0]
[4 5 7 8] [4 5 2 8]
[6 3 5 9] [0 3 9 0]
[2 1 2 5] [4 5 7 8]
[5 6 8 9] [1 1 2 5]
[1 1 2 4] [4 5 7 8]
[8 5 9 0] [8 5 9 0]
[3 3 5 6] [3 6 8 6]
[5 6 8 9] [8 5 9 0]
[6 3 5 9] [9 6 8 9]
[5 6 8 9] [6 6 8 9]
[2 1 2 5] [2 1 2 9]
[7 4 5 8] [3 5 2 8]
[0 8 9 0] [0 4 9 0]
[5 6 8 9] [0 6 9 0]
[6 3 5 9] [9 3 8 9]
[1 1 2 4] [4 4 5 8]
[9 6 8 9] [3 6 5 9]
[4 5 7 8] [4 5 7 8]
[2 1 2 5] [0 3 5 8]
[7 4 5 8] [7 4 5 8]
[3 3 5 6] [3 3 5 9]
[9 6 8 9] [6 3 5 9]
[1 1 2 4] [4 5 2 8]
[9 6 8 

Gyro_25_window_66b325&b56522_75.csv : [9 6 8 9] [4 3 5 9]
[6 3 5 9] [3 6 5 9]
[6 3 5 9] [3 3 5 6]
[4 5 7 8] [4 5 2 8]
[4 5 7 8] [2 5 2 0]
[1 1 2 4] [7 4 5 8]
[3 3 5 6] [0 3 5 9]
[8 5 9 0] [0 8 9 0]
[1 1 2 4] [4 4 5 8]
[1 1 2 4] [1 5 7 8]
[9 6 8 9] [6 3 5 9]
[7 4 5 8] [2 1 2 5]
[4 5 7 8] [1 1 7 8]
[7 4 5 8] [3 3 5 9]
[0 8 9 0] [0 6 9 0]
[3 3 5 6] [0 5 5 0]
[6 3 5 9] [6 6 5 9]
[4 5 7 8] [4 1 2 8]
[6 3 5 9] [9 6 5 9]
[6 3 5 9] [6 3 5 9]
[8 5 9 0] [5 6 8 9]
[9 6 8 9] [3 6 5 9]
[6 3 5 9] [7 5 5 0]
[9 6 8 9] [9 6 9 0]
[5 6 8 9] [5 5 9 9]
[4 5 7 8] [1 4 7 8]
[6 3 5 9] [3 6 5 9]
[2 1 2 5] [7 5 7 8]
[5 6 8 9] [4 1 2 8]
[1 1 2 4] [4 5 7 8]
[8 5 9 0] [8 5 9 0]
[3 3 5 6] [3 6 2 5]
[5 6 8 9] [0 8 9 0]
[6 3 5 9] [9 3 8 9]
[5 6 8 9] [9 3 9 9]
[2 1 2 5] [9 6 8 8]
[7 4 5 8] [5 5 5 5]
[0 8 9 0] [0 8 5 0]
[5 6 8 9] [8 5 9 0]
[6 3 5 9] [6 3 5 9]
[1 1 2 4] [7 5 7 8]
[9 6 8 9] [6 3 5 9]
[4 5 7 8] [4 5 7 8]
[2 1 2 5] [7 3 5 9]
[7 4 5 8] [7 4 5 9]
[3 3 5 6] [2 6 8 9]
[9 6 8 9] [6 3 5 9]
[1 1 2 4] [4 5 2 4]
[9

Gyro_30_4vuni_66b325&b56522_9.csv : [9 6 8 9] [9 3 5 9]
[6 3 5 9] [8 3 5 9]
[6 3 5 9] [8 3 5 0]
[4 5 7 8] [2 1 7 8]
[4 5 7 8] [4 5 7 8]
[1 1 2 4] [1 1 2 4]
[3 3 5 6] [9 3 5 9]
[8 5 9 0] [3 3 9 6]
[1 1 2 4] [4 1 7 8]
[1 1 2 4] [1 1 2 4]
[9 6 8 9] [8 8 9 0]
[7 4 5 8] [7 8 5 0]
[4 5 7 8] [4 1 2 8]
[7 4 5 8] [8 6 5 9]
[0 8 9 0] [0 8 9 0]
[3 3 5 6] [9 5 5 9]
[6 3 5 9] [3 3 5 6]
[4 5 7 8] [7 4 5 8]
[6 3 5 9] [5 5 5 9]
[6 3 5 9] [6 3 5 6]
[8 5 9 0] [5 6 5 0]
[9 6 8 9] [8 3 5 9]
[6 3 5 9] [3 3 9 0]
[9 6 8 9] [6 3 5 9]
[5 6 8 9] [8 6 8 9]
[4 5 7 8] [4 1 7 8]
[6 3 5 9] [0 3 5 9]
[2 1 2 5] [3 6 5 9]
[5 6 8 9] [2 1 2 8]
[1 1 2 4] [1 5 7 8]
[8 5 9 0] [8 3 9 0]
[3 3 5 6] [8 3 5 0]
[5 6 8 9] [6 3 8 9]
[6 3 5 9] [6 3 5 9]
[5 6 8 9] [6 3 5 0]
[2 1 2 5] [2 1 2 5]
[7 4 5 8] [4 5 7 8]
[0 8 9 0] [3 8 8 0]
[5 6 8 9] [3 3 8 0]
[6 3 5 9] [6 6 5 6]
[1 1 2 4] [4 1 2 4]
[9 6 8 9] [6 3 5 9]
[4 5 7 8] [4 5 7 8]
[2 1 2 5] [2 1 2 5]
[7 4 5 8] [0 4 5 8]
[3 3 5 6] [3 3 5 9]
[9 6 8 9] [8 5 9 9]
[1 1 2 4] [4 5 7 8]
[9 6

Gyro_30_4v_66b325&b56522_9.csv : [9 6 8 9] [2 3 9 0]
[6 3 5 9] [7 6 5 8]
[6 3 5 9] [3 3 5 9]
[4 5 7 8] [2 1 2 8]
[4 5 7 8] [2 5 2 8]
[1 1 2 4] [1 4 5 8]
[3 3 5 6] [0 5 8 6]
[8 5 9 0] [0 6 9 0]
[1 1 2 4] [7 5 5 8]
[1 1 2 4] [4 5 7 8]
[9 6 8 9] [6 6 8 9]
[7 4 5 8] [2 1 2 5]
[4 5 7 8] [4 1 2 8]
[7 4 5 8] [6 3 5 9]
[0 8 9 0] [0 8 9 0]
[3 3 5 6] [8 6 8 9]
[6 3 5 9] [6 3 8 9]
[4 5 7 8] [4 4 2 4]
[6 3 5 9] [6 3 5 9]
[6 3 5 9] [6 3 5 9]
[8 5 9 0] [5 3 5 9]
[9 6 8 9] [3 3 5 9]
[6 3 5 9] [5 5 5 9]
[9 6 8 9] [8 5 5 9]
[5 6 8 9] [8 6 9 9]
[4 5 7 8] [6 5 8 8]
[6 3 5 9] [9 6 9 9]
[2 1 2 5] [3 5 5 8]
[5 6 8 9] [1 1 2 4]
[1 1 2 4] [4 1 7 8]
[8 5 9 0] [0 6 9 0]
[3 3 5 6] [6 3 5 9]
[5 6 8 9] [8 8 9 0]
[6 3 5 9] [8 3 8 9]
[5 6 8 9] [6 6 8 9]
[2 1 2 5] [3 1 2 9]
[7 4 5 8] [8 3 2 4]
[0 8 9 0] [5 4 5 0]
[5 6 8 9] [8 5 9 0]
[6 3 5 9] [6 3 5 9]
[1 1 2 4] [1 1 7 4]
[9 6 8 9] [9 3 8 9]
[4 5 7 8] [4 5 5 8]
[2 1 2 5] [6 6 5 9]
[7 4 5 8] [2 1 5 9]
[3 3 5 6] [5 3 5 6]
[9 6 8 9] [9 3 5 9]
[1 1 2 4] [4 5 7 8]
[9 6 8 

Gyro_30_window_66b325&b56522_90.csv : [9 6 8 9] [9 3 5 8]
[6 3 5 9] [3 3 5 9]
[6 3 5 9] [6 3 5 9]
[4 5 7 8] [4 1 5 9]
[4 5 7 8] [9 6 8 9]
[1 1 2 4] [1 4 2 8]
[3 3 5 6] [5 8 9 9]
[8 5 9 0] [0 8 5 0]
[1 1 2 4] [4 5 2 8]
[1 1 2 4] [4 5 2 8]
[9 6 8 9] [6 6 5 9]
[7 4 5 8] [2 6 2 0]
[4 5 7 8] [1 1 2 8]
[7 4 5 8] [6 6 5 8]
[0 8 9 0] [0 5 8 0]
[3 3 5 6] [8 8 9 0]
[6 3 5 9] [6 3 5 9]
[4 5 7 8] [7 5 2 8]
[6 3 5 9] [9 6 8 9]
[6 3 5 9] [6 3 5 9]
[8 5 9 0] [0 6 8 9]
[9 6 8 9] [3 3 5 9]
[6 3 5 9] [0 5 5 8]
[9 6 8 9] [6 6 9 9]
[5 6 8 9] [0 5 8 0]
[4 5 7 8] [7 5 5 8]
[6 3 5 9] [9 3 5 9]
[2 1 2 5] [2 4 7 8]
[5 6 8 9] [1 5 2 9]
[1 1 2 4] [4 5 7 4]
[8 5 9 0] [8 5 9 0]
[3 3 5 6] [3 3 5 6]
[5 6 8 9] [8 5 9 0]
[6 3 5 9] [6 6 8 9]
[5 6 8 9] [6 6 5 9]
[2 1 2 5] [2 6 8 9]
[7 4 5 8] [4 5 2 8]
[0 8 9 0] [7 8 9 0]
[5 6 8 9] [8 5 9 0]
[6 3 5 9] [6 3 5 9]
[1 1 2 4] [7 5 2 8]
[9 6 8 9] [6 6 8 9]
[4 5 7 8] [1 5 7 8]
[2 1 2 5] [0 3 5 0]
[7 4 5 8] [6 4 5 9]
[3 3 5 6] [3 3 8 9]
[9 6 8 9] [6 3 8 9]
[1 1 2 4] [4 5 2 8]
[9

In [5]:
# from sklearn.datasets import make_classification
# from sklearn.multioutput import MultiOutputClassifier
# from sklearn.ensemble import RandomForestClassifier
# from sklearn.utils import shuffle
# import numpy as np
# X, y1 = make_classification(n_samples=10, n_features=100, n_informative=30, n_classes=3, random_state=1)
# y2 = shuffle(y1, random_state=1)
# y3 = shuffle(y1, random_state=2)
# Y = np.vstack((y1, y2, y3)).T
# n_samples, n_features = X.shape # 10,100
# n_outputs = Y.shape[1] # 3
# n_classes = 3
# print(type(Y))
# print(Y)
# forest = RandomForestClassifier(random_state=1)
# multi_target_forest = MultiOutputClassifier(forest, n_jobs=-1)
# multi_target_forest.fit(X, Y).predict(X)